### ISSUE TITLE
Trojan-Downloader.Win32.Bitser infection found in log4j-finder.exe

### ISSUE THREAD

**Issue by JIPI69** [fox-it/log4j-finder#11]
Kaspersky Anti-Virus found this on .exe file

Type: Cheval de Troie
Nom: Trojan-Downloader.Win32.Bitser.cue
Exactitude: Exactement
**Niveau de menace: Élevé**
Type d'objet: Fichier
Nom de l'objet: log4j-finder.exe
Chemin de l'objet: ***********
MD5: 0E08555A17CA3E08D02DBD4CFB87C1AA
Raison: Consigné dans le rapport

Kind regards.
Jipi69

**Comment by JIPI69** [comment]
![Capture d’écran 2021-12-16 à 11 28 53](https://user-images.githubusercontent.com/96235916/146354817-ef315aa6-5e70-4545-a7f7-42eeac166881.png)

**Comment by JIPI69** [comment]
![Capture d’écran 2021-12-16 à 11 31 28](https://user-images.githubusercontent.com/96235916/146355117-bad95103-4232-4c69-a7b1-743f4b506398.png)

**Comment by yunzheng** [comment]
Thanks for sharing, it looks like antivirus products don't like Pyinstaller executables (as to be expected I guess).

I have no better solution for now, other than what #10 suggested to add the instructions to the README.md on how to generate the executable yourself.

**Comment by jkommeren** [comment]
Try building it yourself, that fixed it for me:

Copy log4j-finder.py and log4j-finder.spec from repo
Install Python 3.10
=> pip install pyinstaller
=> pyinstaller log4j-finder.spec

Exe is in your dist folder.

All our virusscanners were blocking the binary listed on frontpage for some reason, the one I generated myself was considered "suspicous", but at least not removed straight away.

Also good to know: For some reason it has big trouble when being run from a Onedrive folder and network drive on our machines (suspect it's because of pyinstaller, but could again be our virusscanner). It will only scan a few files and report it's done. Just copy it to C: and you're good.

**Comment by yunzheng** [comment]
While I cannot help AntiVirus from flagging PyInstaller files, I have added the build instructions to the README.md

Thanks for posting your instructions @jkommeren , I have added some of this in the README.md.

**Comment by jkommeren** [comment]
Np @yunzheng . Greetings from across the road! Primevision is grateful for your work
