### ISSUE TITLE
Access Denied even after elevating cmd 

### ISSUE THREAD

**Issue by laroshkhan** [fox-it/log4j-finder#4]
Hello Team,

Thanks for developing this tool. I was trying to run it on my PC(windows), just installed python and ran it as explained by you, however, I am seeing a lot of access denied(even after opening cmd as admin and running if from there). 

Is there a way to give it privilges?

**Comment by yunzheng** [comment]
I have looked into this issue and it seems it's caused by some special directories, for example:
```
PermissionError: [WinError 5] Access is denied: 'c:/users/Default\\Templates'
```
However when I check this directory myself in `c:/users/default`, there is no `Templates` directory, however I can change directory to it using `cd`, but there is nothing in it. I'm not a Windows expert so I have no idea about this behaviour.

I think it's safe to ignore these Access Denieds, and run without `-v`. However if you do see a file or directory that could not be scanned but should be, let me know!

**Comment by laroshkhan** [comment]
I just tried to run the scan on my whole C drive and used --v to see and it seems to be denied in all of my directories.

![test](https://user-images.githubusercontent.com/16112952/146173851-f17bcbff-a5cb-4bef-bc38-cfedee0c51ec.PNG)

**Comment by Schamper** [comment]
Those are expected errors, since most of those are system directories. You can safely ignore these errors.

**Comment by laroshkhan** [comment]
Thanks for the update. I will keep testing it and will report any issues.
