### ISSUE TITLE
Symantec Endpoint Protection detects as Trojan

### ISSUE THREAD

**Issue by goztrk** [fox-it/log4j-finder#57]
Windows executable version of this repo is being detected as `Trojan.Gen.2`.

Symantec Endpoint Version 14.3.4637.2000
![image](https://user-images.githubusercontent.com/1487670/146715076-ee90fc5c-9a3c-4c6f-8270-a91480f600e9.png)

**Comment by Robby-Swartenbroekx** [comment]
You can see and read the source code. It’s extremely simple to make an exe out of this (I’ve done it for myself because I wanted the output in a slightly different format). If your AV solution thinks it has a problem, this should then be considered as a false positive and handled as such: report to the support of that AV solution and in the mean time make an exclusion for it.

**Comment by Quanthir** [comment]
Yes, I already did that but wanted to inform about the issue.

**Comment by Aleksey-Maksimov** [comment]
7 security vendors and 1 sandbox flagged this file as malicious

![изображение](https://user-images.githubusercontent.com/17614847/147754901-1aad96a4-f382-47b2-af5b-95dd1b1e2b38.png)
